# 开发环境配置
spring:
  thymeleaf:
    cache: false
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.31.40:3306/renting?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8

file:
  #文件上传目录 绝对路径 末尾不需要加 /
#  path: D:/files #windows
  path: /data/files #linux
